[package]
name    = "serial-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex      = "1.9.3"
crossterm  = "0.27.0"
serialport = "4.2.2"
